export const offersData = [
    {
        image: "./img/VolkswagenTiguan.jpg",
        new: null,
        sold: null,
        make: "Volkswagen",
        model: "Tiguan",
        year: "2019",
        mileage: "19.855",
        transmission: "automatic",
        fuel: "diesel",
        price: "34.888",
        available: true
    },
    {
        image: "./img/ToyotaHighlanderXLE.jpg",
        new: true,
        sold: null,
        make: "Toyota",
        model: "Highlander XLE",
        year: "2014",
        mileage: "69.000",
        transmission: "automatic",
        fuel: "gas",
        price: "27.875",
        available: true
    },
    {
        image: "./img/LexusRX350LUXURY.jpg",
        new: null,
        sold: null,
        make: "Lexus",
        model: "RX 350 LUXURY",
        year: "2017",
        mileage: "39.850",
        transmission: "automatic",
        fuel: "gas",
        price: "38.775",
        available: false
    },
    {
        image: "./img/ToyotaHighlanderLEAWD.jpg",
        new: null,
        sold: null,
        make: "Toyota",
        model: "Highlander LE AWD",
        year: "2016",
        mileage: "104.000",
        transmission: "automatic",
        fuel: "gas",
        price: "23.728",
        available: false
    },
    {
        image: "./img/HyundaiElantra.jpg",
        new: null,
        sold: null,
        make: "Hyundai",
        model: "Elantra",
        year: "2017",
        mileage: "95.000",
        transmission: "automatic",
        fuel: "gas",
        price: "11.788",
        available: true
    },
    {
        image: "./img/Mercedes-BenzGLE-Class.jpg",
        new: null,
        sold: null,
        make: "Mercedes-Benz",
        model: "GLE-Class",
        year: "2016",
        mileage: "59.800",
        transmission: "automatic",
        fuel: "diesel",
        price: "38.878",
        available: false
    },
    {
        image: "./img/ToyotaVenzaAWDXLE.jpg",
        new: null,
        sold: true,
        make: "Toyota",
        model: "Venza AWD XLE",
        year: "2015",
        mileage: "99.000",
        transmission: "automatic",
        fuel: "gas",
        price: "18.620",
        available: false
    },
    {
        image: "./img/LexusRX350F-SPORT.jpg",
        new: true,
        sold: null,
        make: "Lexus",
        model: "RX 350 F-SPORT",
        year: "2016",
        mileage: "86.000",
        transmission: "automatic",
        fuel: "gas",
        price: "34.888",
        available: false
    },
    {
        image: "./img/VolkswagenTiguan.jpg",
        new: null,
        sold: null,
        make: "Volkswagen",
        model: "Tiguan",
        year: "2019",
        mileage: "19.855",
        transmission: "automatic",
        fuel: "diesel",
        price: "34.888",
        available: false
    },
    {
        image: "./img/ToyotaHighlanderXLE.jpg",
        new: false,
        sold: null,
        make: "Toyota",
        model: "Highlander XLE",
        year: "2014",
        mileage: "69.000",
        transmission: "automatic",
        fuel: "gas",
        price: "27.875",
        available: false
    },
    {
        image: "./img/LexusRX350LUXURY.jpg",
        new: null,
        sold: null,
        make: "Lexus",
        model: "RX 350 LUXURY",
        year: "2017",
        mileage: "39.850",
        transmission: "automatic",
        fuel: "gas",
        price: "38.775",
        available: false
    },
    {
        image: "./img/ToyotaHighlanderLEAWD.jpg",
        new: null,
        sold: null,
        make: "Toyota",
        model: "Highlander LE AWD",
        year: "2016",
        mileage: "104.000",
        transmission: "automatic",
        fuel: "gas",
        price: "23.728",
        available: false
    },
    {
        image: "./img/VolkswagenTiguan.jpg",
        new: true,
        sold: null,
        make: "Volkswagen",
        model: "Tiguan",
        year: "2019",
        mileage: "19.855",
        transmission: "automatic",
        fuel: "diesel",
        price: "34.888",
        available: false
    },
    {
        image: "./img/ToyotaHighlanderXLE.jpg",
        new: false,
        sold: null,
        make: "Toyota",
        model: "Highlander XLE",
        year: "2014",
        mileage: "69.000",
        transmission: "automatic",
        fuel: "gas",
        price: "27.875",
        available: false
    },
    {
        image: "./img/LexusRX350LUXURY.jpg",
        new: null,
        sold: null,
        make: "Lexus",
        model: "RX 350 LUXURY",
        year: "2017",
        mileage: "39.850",
        transmission: "automatic",
        fuel: "gas",
        price: "38.775",
        available: false
    },
    {
        image: "./img/ToyotaHighlanderLEAWD.jpg",
        new: null,
        sold: null,
        make: "Toyota",
        model: "Highlander LE AWD",
        year: "2016",
        mileage: "104.000",
        transmission: "automatic",
        fuel: "gas",
        price: "23.728",
        available: false
    },
    {
        image: "./img/HyundaiElantra.jpg",
        new: null,
        sold: null,
        make: "Hyundai",
        model: "Elantra",
        year: "2017",
        mileage: "95.000",
        transmission: "automatic",
        fuel: "gas",
        price: "11.788",
        available: false
    },
    {
        image: "./img/Mercedes-BenzGLE-Class.jpg",
        new: null,
        sold: null,
        make: "Mercedes-Benz",
        model: "GLE-Class",
        year: "2016",
        mileage: "59.800",
        transmission: "automatic",
        fuel: "diesel",
        price: "38.878",
        available: false
    },
    {
        image: "./img/ToyotaVenzaAWDXLE.jpg",
        new: null,
        sold: false,
        make: "Toyota",
        model: "Venza AWD XLE",
        year: "2015",
        mileage: "99.000",
        transmission: "automatic",
        fuel: "gas",
        price: "18.620",
        available: false
    },
    {
        image: "./img/LexusRX350F-SPORT.jpg",
        new: true,
        sold: null,
        make: "Lexus",
        model: "RX 350 F-SPORT",
        year: "2016",
        mileage: "86.000",
        transmission: "automatic",
        fuel: "gas",
        price: "34.888",
        available: false
    },
    {
        image: "./img/VolkswagenTiguan.jpg",
        new: null,
        sold: null,
        make: "Volkswagen",
        model: "Tiguan",
        year: "2019",
        mileage: "19.855",
        transmission: "automatic",
        fuel: "diesel",
        price: "34.888",
        available: false
    },
    {
        image: "./img/ToyotaHighlanderXLE.jpg",
        new: null,
        sold: null,
        make: "Toyota",
        model: "Highlander XLE",
        year: "2014",
        mileage: "69.000",
        transmission: "automatic",
        fuel: "gas",
        price: "27.875",
        available: true
    },
];